# Generated by Django 2.2.3 on 2019-07-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pass_gen',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='tg_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
