# Generated by Django 2.2.3 on 2019-07-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass', '0004_auto_20190723_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='home_number',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
