# Generated by Django 2.2.3 on 2019-07-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pass', '0005_person_home_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='otchestvo',
            new_name='patronymic',
        ),
    ]
